<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net472</TargetFramework>
    <Nullable>enable</Nullable>
    <LangVersion>14</LangVersion>

    <!-- VSIX settings -->
    <VSSDKBuildToolsAutoSetup>true</VSSDKBuildToolsAutoSetup>
    <GeneratePkgDefFile>true</GeneratePkgDefFile>
    <UseWPF>true</UseWPF>
    <CopyBuildOutputToOutputDirectory>true</CopyBuildOutputToOutputDirectory>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="ToolboxControl1.xaml" />
  </ItemGroup>
  <ItemGroup>
    <ProjectCapability Include="CreateVsixContainer" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="DocumentFormat.OpenXml" Version="3.5.1" />
    <PackageReference Include="Microsoft.VisualStudio.SDK" Version="17.14.40265" ExcludeAssets="runtime" />
    <PackageReference Include="Microsoft.VSSDK.BuildTools" Version="18.9.820" />
  </ItemGroup>
  <ItemGroup>
    <Reference Include="Microsoft.CSharp" />
    <Reference Include="PresentationCore" />
    <Reference Include="PresentationFramework" />
    <Reference Include="System.Data.DataSetExtensions" />
    <Reference Include="System.Xaml" />
  </ItemGroup>
</Project>
